[build]
  command = "./build.sh"
  functions = "functions"

[dev]
  command = "docker run -p 5000:5000 flask-app"

[[redirects]]
  from = "/predict"
  to = "/.netlify/functions/predict"
  status = 200
